sudo: required
services:
  - docker

before_install:
  - docker build -t zuzutw/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zuzutw/react-test npm run test

after_success:
  - docker build -t zuzutw/multi-client ./client
  - docker build -t zuzutw/multi-nginx ./nginx
  - docker build -t zuzutw/multi-server ./server
  - docker build -t zuzutw/multi-worker ./worker
  # Login to docker hub
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Push the production images to docker hub
  - docker push zuzutw/multi-client
  - docker push zuzutw/multi-nginx
  - docker push zuzutw/multi-server
  - docker push zuzutw/multi-worker


deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-ap-northeast-1-073252906284"
  bucker_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY